# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

exclude: [vendor, "Gemfile", "Gemfile.lock"]

# Site settings
title: Stream of Soliloquies 
email: abhinavrajagopalan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    This is my blog and personal web page where I write mostly about computing, science, philosophy and whatever else I feel like. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://abvr.github.io" # the base hostname & protocol for your site
github_username: abvr

# Build settings
markdown: kramdown
highlighter: rouge
